{"name": "Se observan los campos UserName y Password -- @1.1 ", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: disconnected: not connected to DevTools\n  (failed to check if window was closed: disconnected: not connected to DevTools)\n  (Session info: chrome=112.0.5615.121)\nStacktrace:\nBacktrace:\n\tGetHandleVerifier [0x00F4DCE3+50899]\n\t(No symbol) [0x00EDE111]\n\t(No symbol) [0x00DE5588]\n\t(No symbol) [0x00DD70CB]\n\t(No symbol) [0x00DD778A]\n\t(No symbol) [0x00DD7728]\n\t(No symbol) [0x00DCC37A]\n\t(No symbol) [0x00DCCBD7]\n\t(No symbol) [0x00E33C48]\n\t(No symbol) [0x00E2B8C3]\n\t(No symbol) [0x00E07708]\n\t(No symbol) [0x00E0886D]\n\tGetHandleVerifier [0x011B3EAE+2566302]\n\tGetHandleVerifier [0x011E92B1+2784417]\n\tGetHandleVerifier [0x011E327C+2759788]\n\tGetHandleVerifier [0x00FE5740+672048]\n\t(No symbol) [0x00EE8872]\n\t(No symbol) [0x00EE41C8]\n\t(No symbol) [0x00EE42AB]\n\t(No symbol) [0x00ED71B7]\n\tBaseThreadInitThunk [0x763F7D49+25]\n\tRtlInitializeExceptionChain [0x7762B74B+107]\n\tRtlClearBits [0x7762B6CF+191]\n\n", "trace": "  File \"C:\\ProgramFiles\\Python311\\Lib\\site-packages\\behave\\model.py\", line 1461, in run\n    match.run(runner.context)\n  File \"C:\\ProgramFiles\\Python311\\Lib\\site-packages\\behave\\model.py\", line 1908, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\01Login.py\", line 47, in step_impl\n    context.driver.close()\n  File \"C:\\ProgramFiles\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 551, in close\n    self.execute(Command.CLOSE)\n  File \"C:\\ProgramFiles\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\ProgramFiles\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 243, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given Iniciando Navegador en la Web https://demo.opencart.com/admin", "status": "passed", "start": 1681583536944, "stop": 1681583539271}, {"name": "When Escribiendo campo  Username :\"demo\"", "status": "passed", "start": 1681583539272, "stop": 1681583540345}, {"name": "When Escribiendo campo password :\"demo\"", "status": "passed", "start": 1681583540345, "stop": 1681583544348}, {"name": "When Click en boton Login", "status": "passed", "start": 1681583544348, "stop": 1681583546354}, {"name": "When validar Inicio Sesion", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: disconnected: not connected to DevTools\n  (failed to check if window was closed: disconnected: not connected to DevTools)\n  (Session info: chrome=112.0.5615.121)\nStacktrace:\nBacktrace:\n\tGetHandleVerifier [0x00F4DCE3+50899]\n\t(No symbol) [0x00EDE111]\n\t(No symbol) [0x00DE5588]\n\t(No symbol) [0x00DD70CB]\n\t(No symbol) [0x00DD778A]\n\t(No symbol) [0x00DD7728]\n\t(No symbol) [0x00DCC37A]\n\t(No symbol) [0x00DCCBD7]\n\t(No symbol) [0x00E33C48]\n\t(No symbol) [0x00E2B8C3]\n\t(No symbol) [0x00E07708]\n\t(No symbol) [0x00E0886D]\n\tGetHandleVerifier [0x011B3EAE+2566302]\n\tGetHandleVerifier [0x011E92B1+2784417]\n\tGetHandleVerifier [0x011E327C+2759788]\n\tGetHandleVerifier [0x00FE5740+672048]\n\t(No symbol) [0x00EE8872]\n\t(No symbol) [0x00EE41C8]\n\t(No symbol) [0x00EE42AB]\n\t(No symbol) [0x00ED71B7]\n\tBaseThreadInitThunk [0x763F7D49+25]\n\tRtlInitializeExceptionChain [0x7762B74B+107]\n\tRtlClearBits [0x7762B6CF+191]\n\n", "trace": "  File \"C:\\ProgramFiles\\Python311\\Lib\\site-packages\\behave\\model.py\", line 1461, in run\n    match.run(runner.context)\n  File \"C:\\ProgramFiles\\Python311\\Lib\\site-packages\\behave\\model.py\", line 1908, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\01Login.py\", line 47, in step_impl\n    context.driver.close()\n  File \"C:\\ProgramFiles\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 551, in close\n    self.execute(Command.CLOSE)\n  File \"C:\\ProgramFiles\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\ProgramFiles\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 243, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1681583546354, "stop": 1681583546358}, {"name": "Then Click en cerrar sesion", "status": "skipped", "start": 1681583546358, "stop": 1681583546358}], "parameters": [{"name": "Username", "value": "demo"}, {"name": "Password", "value": "demo"}], "start": 1681583536944, "stop": 1681583546358, "uuid": "e77fe974-e1aa-4ed6-a315-49a8bfcff358", "historyId": "3e596da3f24bcb4b2c908aa3881c142b", "fullName": "Inicio de Sesion con Datos Validos: Se observan los campos UserName y Password", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Inicio de Sesion con Datos Validos"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}